name: Disparo manual

on:
  schedule:
    - cron: '0 8 * * 1-5'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Baixando projeto
        uses: actions/checkout@v4

      - name: Executando teste cypress
        uses: cypress-io/github-action@v6
        with:
          browser: chrome
          spec: cypress/e2e/login.cy.js

      - name: Subindo relatório
        if: always() # Certifique-se de que o relatório será salvo mesmo se os testes falharem
        uses: actions/upload-artifact@v4
        with:
          name: cypress-report # Nome do artifact
          path: mochawesome-report # Caminho onde o relatório está salvo
          retention-days: 3 # Define que o artifact expira em 3 dias
      
      - name: rodar os testes por curl
        run: |
          curl -X POST https://api.github.com/repos/SeuUsuario/SeuRepositorio/actions/workflows/pr-request.yml/dispatches \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref":"master"}'